import re
import json
import logging
from datetime import datetime, timezone, timedelta
from typing import Optional, List, Dict, Any, Tuple
import httpx
from sqlalchemy.orm import Session
from sqlalchemy import func

from config import settings
from models.welfare_case import WelfareCase
from models.personnel import Personnel, Unit
from models.leave import LeaveRecord
from models.duty_roster import DutyRoster
from models.prediction import RiskPrediction
from models.buddy_signal import BuddySignal
from ml.predict import DISPLAY_NAME_MAP

logger = logging.getLogger("prahari.copilot")

class LocalModelUnavailable(RuntimeError):
    """Raised when a Copilot response cannot be generated by the local model."""

# ---------------------------------------------------------------------------
# 1. CLINICAL LEXICON GUARDRAIL (Mental Healthcare Act 2017 Sec 23 & 115 & Defense Norms)
# ---------------------------------------------------------------------------
CLINICAL_LEXICON_RULES: List[Tuple[str, str]] = [
    (r"\bmajor\s+depressive\s+disorder\b", "severe operational stress condition"),
    (r"\bclinical\s+depression\b", "acute operational stress reaction"),
    (r"\bdepression\b", "acute operational stress"),
    (r"\bdepressive\b", "operational fatigue"),
    (r"\bdepressed\b", "severely fatigued and stressed"),
    (r"\bpost[\s-]traumatic\s+stress(?:\s+disorder)?\b", "combat stress reaction"),
    (r"\bptsd\b", "combat stress reaction"),
    (r"\bsuicid(?:e|al)(?:\s+ideation|\s+tendenc(?:y|ies)|\s+thoughts?)?\b", "critical welfare distress"),
    (r"\battempted\s+suicide\b", "critical welfare emergency"),
    (r"\bself[\s-]harm\b", "urgent command welfare intervention"),
    (r"\bmental\s+illness(?:es)?\b", "severe administrative friction"),
    (r"\bmental\s+(?:disorder|disease)s?\b", "operational stress condition"),
    (r"\bmental\s+health\s+(?:disorder|condition|issue|problem)s?\b", "operational welfare concern"),
    (r"\bmental\s+breakdown\b", "acute operational exhaustion"),
    (r"\bmentally\s+ill\b", "experiencing acute operational strain"),
    (r"\bpsychiatric\s+(?:evaluation|assessment)\b", "medical welfare review"),
    (r"\bpsychiatric\s+(?:ward|facility|hospital)\b", "specialized medical recovery facility"),
    (r"\bpsychiatrist\b", "Regimental Medical Officer / Behavioral Specialist"),
    (r"\bpsychiatric\b", "behavioral health"),
    (r"\bpsychosis\b", "acute operational disequilibrium"),
    (r"\bpsychotic\b", "behaviorally distressed"),
    (r"\binsanity\b", "acute operational exhaustion"),
    (r"\blunatic\b", "distressed personnel"),
]

def sanitize_clinical_lexicon(text: str) -> str:
    """
    Sanitizes text by replacing prohibited clinical pathology terms with
    Mental Healthcare Act 2017 (Sec 23 & 115) compliant operational defense terminology.
    """
    if not text:
        return text
    sanitized = text
    for pattern, replacement in CLINICAL_LEXICON_RULES:
        sanitized = re.sub(pattern, replacement, sanitized, flags=re.IGNORECASE)
    return sanitized

def extract_citations(text: str) -> List[str]:
    """
    Extracts all [CITED: SOURCE - DETAIL] or (CITED: SOURCE - DETAIL) citations from text.
    Returns deduplicated list preserving original order.
    """
    if not text:
        return []
    matches = re.findall(r"[\[\(]CITED:\s*([^\n\)\]]+)[\)\]]", text, flags=re.IGNORECASE)
    seen = set()
    ordered_citations = []
    for m in matches:
        clean_citation = m.strip()
        if clean_citation and clean_citation not in seen:
            seen.add(clean_citation)
            ordered_citations.append(clean_citation)
    return ordered_citations

def _format_soldier_title(rank: str, name: str) -> str:
    """Formats rank and name avoiding redundant prefix (e.g. 'Constable Constable Rajesh Kumar')."""
    if name.lower().startswith(rank.lower()):
        return name
    return f"{rank} {name}"

# ---------------------------------------------------------------------------
# 2. EVIDENCE GROUNDER (Dossier Assembly)
# ---------------------------------------------------------------------------
def gather_trooper_dossier(
    db: Session,
    case_id: Optional[str] = None,
    personnel_id: Optional[str] = None
) -> Optional[Dict[str, Any]]:
    """
    Retrieves and correlates all evidence for a soldier:
    - 90-day leave records (approvals/denials, reasons)
    - 30-day duty roster (night shift density, hours, consecutive duty)
    - Latest RiskPrediction + Top 5 SHAP factors
    - Unit buddy signals
    - Service profile (tenure, hard area, transfers)
    """
    welfare_case = None
    if case_id:
        welfare_case = db.query(WelfareCase).filter(WelfareCase.id == case_id).first()
        if welfare_case:
            personnel_id = welfare_case.personnel_id

    if not personnel_id:
        return None

    personnel = db.query(Personnel).filter(Personnel.id == personnel_id).first()
    if not personnel:
        return None

    unit = personnel.unit
    display_name = _format_soldier_title(personnel.rank, personnel.name)

    # 1. 90-day Leave Records
    latest_leave = db.query(func.max(LeaveRecord.applied_date)).filter(LeaveRecord.personnel_id == personnel.id).scalar()
    ref_leave_date = latest_leave if latest_leave else datetime.now().date()
    cutoff_90d = ref_leave_date - timedelta(days=90)

    leaves_90d = db.query(LeaveRecord).filter(
        LeaveRecord.personnel_id == personnel.id,
        LeaveRecord.applied_date >= cutoff_90d
    ).order_by(LeaveRecord.applied_date.desc()).all()

    # Fallback to recent leaves if none in strict 90d window
    if not leaves_90d:
        leaves_90d = db.query(LeaveRecord).filter(
            LeaveRecord.personnel_id == personnel.id
        ).order_by(LeaveRecord.applied_date.desc()).limit(10).all()

    total_applied = len(leaves_90d)
    approved_leaves = [l for l in leaves_90d if l.status == "approved"]
    denied_leaves = [l for l in leaves_90d if l.status == "denied"]
    pending_leaves = [l for l in leaves_90d if l.status == "pending"]

    denial_reasons = [l.denial_reason for l in denied_leaves if l.denial_reason]
    recent_denial_reason = denial_reasons[0] if denial_reasons else "Operational exigency / staffing shortfall"

    # 2. 30-day Duty Rosters
    latest_roster = db.query(func.max(DutyRoster.date)).filter(DutyRoster.personnel_id == personnel.id).scalar()
    ref_roster_date = latest_roster if latest_roster else datetime.now().date()
    cutoff_30d = ref_roster_date - timedelta(days=30)

    rosters_30d = db.query(DutyRoster).filter(
        DutyRoster.personnel_id == personnel.id,
        DutyRoster.date >= cutoff_30d
    ).order_by(DutyRoster.date.asc()).all()

    if not rosters_30d:
        rosters_30d = db.query(DutyRoster).filter(
            DutyRoster.personnel_id == personnel.id
        ).order_by(DutyRoster.date.desc()).limit(30).all()
        rosters_30d.reverse()

    total_shifts = len(rosters_30d)
    night_shifts = sum(1 for r in rosters_30d if r.shift_type == "night")
    split_shifts = sum(1 for r in rosters_30d if r.shift_type == "split")
    day_shifts = sum(1 for r in rosters_30d if r.shift_type == "day")
    rest_shifts = sum(1 for r in rosters_30d if r.shift_type == "off" or r.duty_type == "rest")
    total_hours = sum(float(r.hours) for r in rosters_30d)
    avg_hours = round(total_hours / total_shifts, 1) if total_shifts > 0 else 8.0
    night_density = round(night_shifts / total_shifts, 3) if total_shifts > 0 else 0.0

    # Calculate consecutive duty days without rest
    max_consecutive = 0
    cur_consecutive = 0
    for r in rosters_30d:
        if r.shift_type != "off" and r.duty_type != "rest":
            cur_consecutive += 1
            if cur_consecutive > max_consecutive:
                max_consecutive = cur_consecutive
        else:
            cur_consecutive = 0

    # 3. Latest Risk Prediction & Top 5 SHAP Drivers
    latest_pred = db.query(RiskPrediction).filter(
        RiskPrediction.personnel_id == personnel.id
    ).order_by(RiskPrediction.predicted_at.desc()).first()

    # Never fabricate a prediction: when no stored RiskPrediction exists, abstain
    # explicitly instead of injecting invented score/confidence values.
    prediction_available = latest_pred is not None
    risk_score = float(latest_pred.risk_score) if prediction_available else None
    risk_level = latest_pred.risk_level if prediction_available else "insufficient_evidence"
    confidence = float(latest_pred.confidence_score) if prediction_available else None
    data_quality = float(latest_pred.data_quality_score) if prediction_available else None

    shap_factors = []
    if latest_pred and latest_pred.shap_values:
        raw_shap = latest_pred.shap_values
        if isinstance(raw_shap, str):
            try:
                raw_shap = json.loads(raw_shap)
            except Exception:
                raw_shap = []
        normalized_shap = []
        if isinstance(raw_shap, dict):
            for feat, val in raw_shap.items():
                try:
                    impact_val = float(val) if val is not None else 0.0
                except (ValueError, TypeError):
                    impact_val = 0.0
                normalized_shap.append({
                    "feature": str(feat),
                    "impact": impact_val,
                    "value": val
                })
        elif isinstance(raw_shap, list):
            for item in raw_shap:
                if isinstance(item, dict):
                    try:
                        impact_val = float(item.get("impact", 0.0))
                    except (ValueError, TypeError):
                        impact_val = 0.0
                    normalized_shap.append({
                        "feature": str(item.get("feature", "")),
                        "impact": impact_val,
                        "value": item.get("value")
                    })
                elif isinstance(item, str):
                    normalized_shap.append({
                        "feature": item,
                        "impact": 0.0,
                        "value": None
                    })

        sorted_shap = sorted(
            normalized_shap,
            key=lambda x: abs(float(x.get("impact", 0.0))),
            reverse=True
        )
        for s in sorted_shap[:5]:
            feat = s.get("feature", "")
            shap_factors.append({
                "feature": feat,
                "display_name": DISPLAY_NAME_MAP.get(feat, feat.replace("_", " ").title()),
                "value": s.get("value"),
                "impact": float(s.get("impact", 0.0))
            })

    # 4. Unit Buddy Signals (last 30 days)
    buddy_query = db.query(BuddySignal).filter(BuddySignal.unit_id == personnel.unit_id)
    latest_buddy = db.query(func.max(BuddySignal.submitted_at)).filter(BuddySignal.unit_id == personnel.unit_id).scalar()
    if latest_buddy:
        buddy_cutoff = latest_buddy - timedelta(days=30)
        buddy_query = buddy_query.filter(BuddySignal.submitted_at >= buddy_cutoff)
    buddy_signals = buddy_query.all()
    buddy_count = len(buddy_signals)

    category_counts = {}
    total_concern_level = 0
    for b in buddy_signals:
        category_counts[b.concern_category] = category_counts.get(b.concern_category, 0) + 1
        total_concern_level += b.concern_level
    avg_concern = round(total_concern_level / buddy_count, 1) if buddy_count > 0 else 1.0

    # 5. Build Explicit Citation Evidence Index
    citations_index = [
        f"SERVICE_RECORD - {display_name} ({personnel.service_number}), {personnel.hard_area_months} months in hard-area tenure at {unit.name if unit else 'Station'}",
        f"LEAVE_LOG - {len(denied_leaves)} leave denials out of {total_applied} applications in past 90 days (Recent denial: {recent_denial_reason})",
        f"DUTY_ROSTER - {night_shifts} night shifts out of {total_shifts} shifts logged in past 30 days ({night_density:.1%} density, {avg_hours:.1f}h avg shift)",
        f"DUTY_ROSTER - {max_consecutive} consecutive duty days without mandatory rest cycle",
    ]
    if prediction_available:
        citations_index.append(
            f"PREDICTION_ENGINE - Calibrated stress risk index {risk_score:.2f} ({risk_level.upper()}) with {confidence:.0%} confidence"
        )
    else:
        citations_index.append(
            "PREDICTION_ENGINE - ABSTAINED: insufficient longitudinal evidence; no calibrated score available. "
            "Human welfare contact recommended instead of algorithmic estimation."
        )

    for sf in shap_factors[:3]:
        impact_sign = "+" if sf["impact"] >= 0 else ""
        citations_index.append(f"SHAP_FACTORS - Catalyst '{sf['display_name']}' (Impact: {impact_sign}{sf['impact']:.2f}, Observed: {sf['value']})")

    if buddy_count > 0:
        top_cats = ", ".join(list(category_counts.keys())[:2])
        citations_index.append(f"BUDDY_SIGNALS - Unit {unit.name if unit else 'HQ'} logged {buddy_count} peer signals in 30 days (Key concerns: {top_cats})")
    else:
        citations_index.append(f"BUDDY_SIGNALS - Unit {unit.name if unit else 'HQ'} peer signals baseline within normal threshold")

    try:
        from services.conflict_service import analyze_evidence_conflict
        conflict_rep = analyze_evidence_conflict(db, personnel.id)
        citations_index.append(f"EVIDENCE_CONFLICT - {conflict_rep.conflict_type} (Severity: {conflict_rep.severity}, Org Burden: {conflict_rep.organizational_burden_score:.2f}, Self Strain: {conflict_rep.self_reported_strain_score:.2f})")
    except Exception as e:
        logger.warning(f"Failed to analyze evidence conflict: {e}")

    try:
        from services.trend_service import analyze_personnel_trend
        trend_rep = analyze_personnel_trend(db, personnel.id)
        citations_index.append(f"LONGITUDINAL_TREND - {trend_rep.trajectory_classification} (Risk velocity: {trend_rep.velocity_score:+.2f}/30d, 30d Delta: {trend_rep.delta_risk:+.2f})")
    except Exception as e:
        logger.warning(f"Failed to analyze trend: {e}")

    return {
        "case_id": case_id or (welfare_case.id if welfare_case else "N/A"),
        "personnel": {
            "id": personnel.id,
            "name": personnel.name,
            "display_name": display_name,
            "rank": personnel.rank,
            "service_number": personnel.service_number,
            "unit_name": unit.name if unit else "Unit HQ",
            "operational_area": unit.operational_area if unit else "semi-hard",
            "hard_area_months": personnel.hard_area_months,
            "total_transfers": personnel.total_transfers,
            "current_posting_date": str(personnel.current_posting_date)
        },
        "leaves": {
            "total_applied": total_applied,
            "approved": len(approved_leaves),
            "denied": len(denied_leaves),
            "pending": len(pending_leaves),
            "recent_denial_reason": recent_denial_reason
        },
        "roster": {
            "total_shifts": total_shifts,
            "night_shifts": night_shifts,
            "split_shifts": split_shifts,
            "day_shifts": day_shifts,
            "rest_shifts": rest_shifts,
            "night_density": night_density,
            "total_hours": total_hours,
            "avg_hours": avg_hours,
            "max_consecutive": max_consecutive
        },
        "prediction": {
            "available": prediction_available,
            "risk_score": risk_score,
            "risk_level": risk_level,
            "confidence": confidence,
            "data_quality": data_quality,
            "abstention_reason": None if prediction_available else "No stored calibrated prediction for this personnel; model abstained per insufficient-evidence guardrail.",
            "shap_factors": shap_factors
        },
        "buddy": {
            "count_30d": buddy_count,
            "category_counts": category_counts,
            "avg_concern": avg_concern
        },
        "citations_index": citations_index
    }

# ---------------------------------------------------------------------------
# 3. LOCAL INTELLIGENCE ENGINE (Ollama Local AI Engine)
# ---------------------------------------------------------------------------
async def query_ollama(prompt: str, system_prompt: Optional[str] = None) -> Tuple[Optional[str], str]:
    """
    Asynchronously queries local Ollama instance at config.OLLAMA_BASE_URL.
    Dynamically identifies installed local models (defaulting to settings.OLLAMA_MODEL)
    and strictly generates responses using local AI with zero hardcoded templates.
    """
    base_url = settings.OLLAMA_BASE_URL.rstrip('/')
    target_model = settings.OLLAMA_MODEL
    timeout = httpx.Timeout(60.0, connect=3.0)

    models_to_try = [target_model]
    try:
        async with httpx.AsyncClient(timeout=httpx.Timeout(3.0, connect=1.5)) as client:
            tags_resp = await client.get(f"{base_url}/api/tags")
            if tags_resp.status_code == 200:
                avail = [m.get("name") for m in tags_resp.json().get("models", []) if m.get("name")]
                for m_name in avail:
                    if m_name not in models_to_try:
                        models_to_try.append(m_name)
    except Exception:
        pass

    messages = []
    if system_prompt:
        messages.append({"role": "system", "content": system_prompt})
    messages.append({"role": "user", "content": prompt})

    async with httpx.AsyncClient(timeout=timeout) as client:
        for model in models_to_try:
            try:
                # 1. Try Chat API (Qwen ChatML formatting)
                chat_payload = {
                    "model": model,
                    "messages": messages,
                    "stream": False,
                    "options": {
                        "temperature": 0.2,
                        "top_p": 0.85,
                        "repeat_penalty": 1.2,
                        "num_ctx": 4096,
                        "num_predict": 1024
                    }
                }
                chat_resp = await client.post(f"{base_url}/api/chat", json=chat_payload)
                if chat_resp.status_code == 200:
                    msg = chat_resp.json().get("message", {}).get("content", "").strip()
                    if msg:
                        return msg, model

                # 2. Fallback to Generate API if Chat API is unsupported
                full_prompt = f"{system_prompt}\n\n{prompt}" if system_prompt else prompt
                gen_payload = {
                    "model": model,
                    "prompt": full_prompt,
                    "stream": False,
                    "options": {
                        "temperature": 0.2,
                        "top_p": 0.85,
                        "repeat_penalty": 1.2,
                        "num_ctx": 4096,
                        "num_predict": 1024
                    }
                }
                gen_resp = await client.post(f"{base_url}/api/generate", json=gen_payload)
                if gen_resp.status_code == 200:
                    msg = gen_resp.json().get("response", "").strip()
                    if msg:
                        return msg, model
            except Exception as e:
                logger.warning("Local Ollama request for model %s failed: %s", model, e)
                continue

    return None, target_model

async def query_llm(prompt: str, system_prompt: Optional[str] = None) -> Tuple[str, str]:
    """
    Local-only AI engine dispatcher. All responses are strictly generated by local AI.
    No hardcoded templates, no canned fallback.
    """
    logger.info(f"Dispatching prompt to Local Ollama ({settings.OLLAMA_MODEL})...")
    resp, model_used = await query_ollama(prompt, system_prompt=system_prompt)
    if resp and len(resp.strip()) > 30:
        return resp.strip(), model_used

    raise LocalModelUnavailable(
        f"Local model '{model_used}' did not return a usable response. "
        "Please ensure Ollama is running and has the model installed."
    )

async def generate_copilot_brief(
    db: Session,
    case_id: Optional[str] = None,
    personnel_id: Optional[str] = None,
    focus_areas: Optional[List[str]] = None,
    custom_instructions: Optional[str] = None
) -> Dict[str, Any]:
    """
    Main entry point for a grounded brief generated strictly by the local AI engine.
    Zero hardcoded templates.
    """
    dossier = gather_trooper_dossier(db, case_id=case_id, personnel_id=personnel_id)
    if not dossier:
        raise ValueError("Target case or personnel not found in database")

    # Construct System Prompt & Grounded Evidence Package
    evidence_text = "\n".join([f"- [CITED: {c}]" for c in dossier["citations_index"]])
    system_prompt = """You are PRAHARI Defense Local AI Copilot, an operational decision-support intelligence engine for Indian Armed Forces and Paramilitary Welfare Officers.
Generate a structured welfare intelligence brief based strictly on the verified evidence dossier.

STRICT OPERATIONAL DIRECTIVES:
1. MHA Clinical Lexicon Compliance (Mental Healthcare Act 2017):
   NEVER use clinical or psychiatric pathology labels (prohibited: depression, ptsd, suicide, mental illness, psychiatric).
   ALWAYS use operational stress and administrative terms: 'acute operational stress', 'severe administrative friction', 'roster burnout', 'sleep debt accumulation', 'critical welfare distress'.
2. Strict Citation Grounding:
   Every factual claim MUST include an exact inline citation tag in the format: [CITED: SOURCE - DETAIL].
   Valid sources: LEAVE_LOG, DUTY_ROSTER, PREDICTION_ENGINE, SHAP_FACTORS, BUDDY_SIGNALS, SERVICE_RECORD.
3. Write in clear, simple, plain English with short, active sentences and clear bullet points."""

    user_prompt = f"""Generate a structured intelligence brief for this soldier with the following sections:
# PRAHARI DEFENSE WELFARE BRIEF
## 1. SOLDIER PROFILE & CURRENT SITUATION
## 2. LEAVE STATUS & FAMILY WORRIES
## 3. DUTY SCHEDULE & LACK OF SLEEP
## 4. MAIN REASONS IDENTIFIED BY AI (ROOT CAUSES)
## 5. UNIT ENVIRONMENT & BUDDY OBSERVATIONS
## 6. RECOMMENDED WELFARE ACTIONS (ACTION STEPS)

VERIFIED EVIDENCE DOSSIER:
{evidence_text}

PERSONNEL PARTICULARS:
- Soldier: {dossier['personnel']['display_name']} ({dossier['personnel']['service_number']})
- Unit: {dossier['personnel']['unit_name']} ({dossier['personnel']['operational_area']})
- Tenure in Hard Area: {dossier['personnel']['hard_area_months']} months | Transfers: {dossier['personnel']['total_transfers']}
- Leaves (90d): {dossier['leaves']['denied']} denied out of {dossier['leaves']['total_applied']} applied (Reason: {dossier['leaves']['recent_denial_reason']})
- Rosters (30d): {dossier['roster']['night_shifts']} night shifts / {dossier['roster']['total_shifts']} shifts ({dossier['roster']['night_density']:.1%} density, {dossier['roster']['avg_hours']:.1f}h/shift, {dossier['roster']['max_consecutive']} consecutive days)
- Risk Prediction: {f"Score {dossier['prediction']['risk_score']:.2f}, Level {dossier['prediction']['risk_level'].upper()}, Confidence {dossier['prediction']['confidence']:.0%}" if dossier['prediction']['available'] else "ABSTAINED — insufficient longitudinal evidence; no calibrated score. Rely on human welfare assessment."}
- Top SHAP Driver: {dossier['prediction']['shap_factors'][0]['display_name'] if dossier['prediction']['shap_factors'] else 'Deployment tenure'}
- Unit Buddy Signals (30d): {dossier['buddy']['count_30d']} signals
"""
    if custom_instructions:
        user_prompt += f"\nADDITIONAL COMMAND DIRECTIVE: {custom_instructions}\n"

    user_prompt += "\nProduce the complete intelligence brief now."

    # Strictly query local AI engine - zero hardcoded fallback templates
    raw_response, model_used = await query_llm(user_prompt, system_prompt=system_prompt)
    sanitized_response = sanitize_clinical_lexicon(raw_response)
    cited_sources = extract_citations(sanitized_response)
    if len(cited_sources) < 2:
        cited_sources = dossier["citations_index"]

    return {
        "case_id": dossier["case_id"],
        "personnel_id": dossier["personnel"]["id"],
        "personnel_name": dossier["personnel"]["name"],
        "personnel_rank": dossier["personnel"]["rank"],
        "unit_name": dossier["personnel"]["unit_name"],
        "risk_level": dossier["prediction"]["risk_level"],
        "risk_score": dossier["prediction"]["risk_score"],
        "brief_markdown": sanitized_response,
        "cited_sources": cited_sources,
        "is_fallback": False,
        "model_used": model_used,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "evidence_summary": {
            "leaves": dossier["leaves"],
            "roster": dossier["roster"],
            "prediction": {
                "risk_score": dossier["prediction"]["risk_score"],
                "risk_level": dossier["prediction"]["risk_level"],
                "top_shap": [s["display_name"] for s in dossier["prediction"]["shap_factors"][:3]]
            },
            "buddy_count_30d": dossier["buddy"]["count_30d"]
        }
    }

# ---------------------------------------------------------------------------
# 5. CONTEXTUAL WELFARE CHAT
# ---------------------------------------------------------------------------
async def chat_with_copilot(
    db: Session,
    message: str,
    case_id: Optional[str] = None,
    personnel_id: Optional[str] = None,
    conversation_history: Optional[List[Dict[str, str]]] = None
) -> Dict[str, Any]:
    """
    Answers operational welfare queries from Welfare Officers, Commanders, or Troopers
    strictly generated by local AI grounded in trooper dossiers and defense welfare regulations.
    """
    dossier = None
    if case_id or personnel_id:
        dossier = gather_trooper_dossier(db, case_id=case_id, personnel_id=personnel_id)

    # Prepare Context
    context_str = ""
    citations_pool = []
    if dossier:
        citations_pool = dossier["citations_index"]
        p = dossier["personnel"]
        lv = dossier["leaves"]
        rs = dossier["roster"]
        pr = dossier["prediction"]
        context_str = f"""
TARGET SOLDIER DOSSIER:
- Subject: {p['display_name']} ({p['service_number']}), Unit {p['unit_name']}
- Stress Risk Level: {pr['risk_level'].upper()} {f"(Risk Index: {pr['risk_score']:.2f}) [CITED: PREDICTION_ENGINE - Calibrated stress risk index {pr['risk_score']:.2f}]" if pr.get('available') else "[PREDICTION_ENGINE abstained — no calibrated score; insufficient evidence]"}
- 90d Leave Status: {lv['denied']} denied / {lv['total_applied']} applied (Recent reason: {lv['recent_denial_reason']}) [CITED: LEAVE_LOG - {lv['denied']} leave denials in 90 days]
- 30d Duty Roster: {rs['night_shifts']} night shifts / {rs['total_shifts']} shifts ({rs['night_density']:.1%} night density, {rs['avg_hours']:.1f}h/day, {rs['max_consecutive']} consecutive duty days) [CITED: DUTY_ROSTER - {rs['night_shifts']} night shifts, {rs['max_consecutive']} consecutive duty days]
- Top SHAP Drivers: {', '.join([s['display_name'] for s in pr['shap_factors'][:3]])}
"""
    else:
        context_str = """
GENERAL DEFENSE WELFARE & STATUTORY REGULATIONS:
- MHA Standing Order SO-04: Mandatory 8-hour continuous circadian rest barrier between armed shifts; sentry shift rotation required for 3+ consecutive night watches.
- 72-Hour Fast-Track Emergency Leave: Urgent domestic distress or family medical crisis requests carry a guaranteed 72-hour priority countdown, escalating to Battalion 2IC / Welfare Officer.
- Section 21 of Mental Healthcare Act 2017: Non-punitive welfare doctrine; seeking counseling or medical welfare review cannot impact ACR, weapons entitlement, or promotions.
- Unit Resilience Optimizer (URO): Equal-trade shift swapping (GD with GD, Armorer with Armorer).
- Tele-MANAS: National 24x7 psychological support helpline 14416.
"""

    system_prompt = """You are PRAHARI Defense Local AI Copilot, assisting a military Welfare Officer, Commander, or Trooper.
Answer the operational question directly, concisely, and practically in 2 to 4 clear bullet points based on the verified soldier dossier or defense welfare regulations.

STRICT OPERATIONAL RULES:
1. MHA Clinical Lexicon Compliance (Mental Healthcare Act 2017):
   - NEVER use psychiatric pathology labels (prohibited: depression, ptsd, suicide, mental illness, psychiatric).
   - ALWAYS use operational stress terms: 'acute operational stress', 'administrative friction', 'roster burnout', 'sleep debt accumulation', 'critical welfare distress'.
2. Ground factual statements with [CITED: SOURCE - DETAIL] citations where applicable.
3. Recommend actionable command solutions: Unit Resilience Optimizer (URO) shift swaps, leave sanctions, peer buddy pairing, and routine RMO health consultations.
4. Keep answers concise, factual, and formatted with bullet points. Avoid conversational filler."""

    user_prompt = f"""{context_str}

USER QUESTION: {message}

Provide a direct, practical, and grounded answer now:"""

    # Strictly query local AI engine - zero hardcoded fallback templates
    raw_response, model_used = await query_llm(user_prompt, system_prompt=system_prompt)
    sanitized = sanitize_clinical_lexicon(raw_response)
    citations = extract_citations(sanitized)
    if not citations and citations_pool:
        citations = citations_pool[:3]

    return {
        "response": sanitized,
        "reply": sanitized,
        "case_id": case_id,
        "personnel_id": personnel_id or (dossier["personnel"]["id"] if dossier else None),
        "cited_sources": citations,
        "is_fallback": False,
        "model_used": model_used,
        "generated_at": datetime.now(timezone.utc).isoformat()
    }