/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        goi: {
          navy: "#0c3866",
          "navy-dark": "#072648",
          saffron: "#ff9933",
          "saffron-dark": "#e65100",
          green: "#138808",
          "green-dark": "#0d6506",
          ashoka: "#000080",
          background: "#f8fafc",
          surface: "#ffffff",
          border: "#cbd5e1",
          "border-light": "#e2e8f0",
          text: "#0f172a",
          "text-muted": "#475569",
        },
        // PRAHARI public-service interface tokens
        m3: {
          surface: "#f4f7fa",
          "surface-dim": "#e9eef3",
          "surface-bright": "#ffffff",
          "surface-container-lowest": "#ffffff",
          "surface-container-low": "#f8fafc",
          "surface-container": "#ffffff",
          "surface-container-high": "#edf4f8",
          "surface-container-highest": "#dce9f1",
          "on-surface": "#1c2c3a",
          "on-surface-variant": "#60717f",
          outline: "#aebfcb",
          "outline-variant": "#d8e2e8",
          primary: "#07558a",
          "on-primary": "#ffffff",
          "primary-container": "#dceff9",
          "on-primary-container": "#063f67",
          secondary: "#087c9d",
          "on-secondary": "#ffffff",
          "secondary-container": "#d9f1f6",
          "on-secondary-container": "#07566d",
          tertiary: "#315da8",
          "on-tertiary": "#ffffff",
          "tertiary-container": "#e1eafe",
          "on-tertiary-container": "#294d89",
          error: "#b42318",
          "on-error": "#ffffff",
          "error-container": "#fee4e2",
          "on-error-container": "#8a1c13",
          "inverse-surface": "#1c2c3a",
          "inverse-on-surface": "#ffffff",
        },
        // Backward-compatibility mapped to M3 tone levels
        defense: {
          900: "#0e1520",
          800: "#152132",
          700: "#1b2a3f",
          600: "#22354e",
          500: "#2d4464",
          accent: "#38bdf8",
          olive: "#3f5235",
          sand: "#e8d8b8"
        },
        risk: {
          green: "#16794a",
          "green-container": "#dcfce7",
          "on-green-container": "#146c43",
          yellow: "#a15c00",
          "yellow-container": "#fff4d6",
          "on-yellow-container": "#7b4700",
          orange: "#b54708",
          "orange-container": "#ffead5",
          "on-orange-container": "#93370d",
          red: "#b42318",
          "red-container": "#fee4e2",
          "on-red-container": "#8a1c13"
        }
      },
      borderRadius: {
        "m3-xs": "4px",
        "m3-sm": "8px",
        "m3-md": "12px",
        "m3-lg": "16px",
        "m3-xl": "20px",
        "m3-2xl": "24px",
        "m3-3xl": "28px",
        "m3-full": "9999px"
      },
      boxShadow: {
        "m3-1": "0px 1px 3px 1px rgba(0, 0, 0, 0.3), 0px 1px 2px 0px rgba(0, 0, 0, 0.4)",
        "m3-2": "0px 2px 6px 2px rgba(0, 0, 0, 0.3), 0px 1px 2px 0px rgba(0, 0, 0, 0.4)",
        "m3-3": "0px 4px 8px 3px rgba(0, 0, 0, 0.3), 0px 1px 3px 0px rgba(0, 0, 0, 0.4)",
        "m3-4": "0px 6px 10px 4px rgba(0, 0, 0, 0.3), 0px 2px 3px 0px rgba(0, 0, 0, 0.4)",
        "m3-5": "0px 8px 12px 6px rgba(0, 0, 0, 0.3), 0px 4px 4px 0px rgba(0, 0, 0, 0.4)",
        "glow-cyan": "0 0 20px -3px rgba(6, 182, 212, 0.35)",
        "glow-emerald": "0 0 20px -3px rgba(16, 185, 129, 0.35)",
        "glow-rose": "0 0 20px -3px rgba(244, 63, 94, 0.45)",
        "glow-amber": "0 0 20px -3px rgba(245, 158, 11, 0.4)",
      },
      fontFamily: {
        sans: [
          'var(--font-noto-sans)',
          '"Noto Sans"',
          'var(--font-noto-devanagari)',
          '"Noto Sans Devanagari"',
          'var(--font-noto-tamil)',
          '"Noto Sans Tamil"',
          'var(--font-open-sans)',
          '"Open Sans"',
          '-apple-system',
          'BlinkMacSystemFont',
          '"Segoe UI"',
          'Roboto',
          '"Helvetica Neue"',
          'Arial',
          'sans-serif'
        ],
        heading: [
          'var(--font-noto-sans)',
          '"Noto Sans"',
          'var(--font-noto-devanagari)',
          '-apple-system',
          'BlinkMacSystemFont',
          '"Segoe UI"',
          'Roboto',
          'sans-serif'
        ],
        mono: [
          'var(--font-mono)',
          '"JetBrains Mono"',
          '"SF Mono"',
          'Consolas',
          '"Courier New"',
          'monospace'
        ],
      },
      keyframes: {
        "fade-in": {
          "0%": { opacity: "0", transform: "translateY(4px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "slide-down": {
          "0%": { opacity: "0", transform: "translateY(-8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "pulse-subtle": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.6" },
        },
        "badge-pulse": {
          "0%, 100%": { transform: "scale(1)" },
          "50%": { transform: "scale(1.05)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
      },
      animation: {
        "fade-in": "fade-in 0.3s ease-out forwards",
        "slide-down": "slide-down 0.25s ease-out forwards",
        "pulse-subtle": "pulse-subtle 2.5s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "badge-pulse": "badge-pulse 2s ease-in-out infinite",
        shimmer: "shimmer 2s infinite linear",
      },
    },
  },
  plugins: [],
}
